---
detectors:
  FeatureEnvy:
    exclude:
    - Auther::BaseController#store_credentials
    - Auther::Gatekeeper#account_authenticated?
  InstanceVariableAssumption:
    exclude:
    - Auther::BaseController
  TooManyStatements:
    exclude:
    - initialize
    - Auther::BaseController#create
    - Auther::Gatekeeper#account_authenticated?
    - Auther::Gatekeeper#account_authorized?
    - Auther::Gatekeeper#call
    - Auther::Gatekeeper#find_account
  UtilityFunction:
    exclude:
    - Auther::BaseController#settings
    - Auther::Gatekeeper#clean_paths
  Attribute:
    exclude:
    - Auther::Presenter::Account#login
    - Auther::Presenter::Account#name
    - Auther::Presenter::Account#password
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    exclude:
    - Auther::Authenticator#authentic?
    - Auther::Gatekeeper#log_authentication
    - Auther::Gatekeeper#log_authorization
  DuplicateMethodCall:
    exclude:
    - Auther::Gatekeeper#authenticated?
    - Auther::Gatekeeper#call
    - Auther::InstallGenerator#install_initializer
  LongParameterList:
    exclude:
    - Auther::Gatekeeper#log_authorization
    - Auther::Settings#initialize
  TooManyMethods:
    exclude:
    - Auther::Gatekeeper
  TooManyInstanceVariables:
    exclude:
    - Auther::Settings
