Style/AndOr:
  EnforcedStyle: conditionals
Style/CaseIndentation:
  IndentOneStep: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/VariableNumber:
  EnforcedStyle: snake_case
Metrics/AbcSize:
  Exclude:
    - "app/controllers/auther/base_controller.rb"
    - "lib/auther/gatekeeper.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*"
Metrics/LineLength:
  Max: 120
  Exclude:
    - "spec/lib/auther/settings_spec.rb"
    - "spec/models/account_spec.rb"
    - "spec/lib/auther/gatekeeper_spec.rb"
    - "spec/lib/auther/cipher_spec.rb"
    - "spec/lib/auther/authenticator_spec.rb"
    - "spec/support/dummy/config/initializers/auther.rb"
    - "spec/support/dummy/config/secrets.yml"
Metrics/MethodLength:
  Exclude:
    - "lib/auther/settings.rb"
Metrics/ParameterLists:
  Exclude:
    - "lib/auther/settings.rb"
