inherit_from:
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/ruby.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/rake.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/performance.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/main/configurations/rubocop/rspec.yml

Layout/RedundantLineBreak:
  Exclude:
    - "spec/support/fixtures/config/routes.rb"

Lint/EmptyBlock:
  Exclude:
    - "spec/support/fixtures/config/routes.rb"
