inherit_gem:
  caliber: config/all.yml

Layout/RedundantLineBreak:
  Exclude:
    - "spec/support/fixtures/config/routes.rb"

Lint/EmptyBlock:
  Exclude:
    - "spec/support/fixtures/config/routes.rb"
