Style/CaseIndentation:
  IndentOneStep: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%r": "()"
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/AbcSize:
  Exclude:
    - "app/controllers/auther/base_controller.rb"
    - "lib/auther/gatekeeper.rb"
Metrics/LineLength:
  Max: 120
  Exclude:
    - "spec/lib/auther/settings_spec.rb"
    - "spec/models/account_spec.rb"
    - "spec/lib/auther/gatekeeper_spec.rb"
    - "spec/lib/auther/cipher_spec.rb"
    - "spec/lib/auther/authenticator_spec.rb"
    - "spec/dummy/config/initializers/auther.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/auther/settings.rb"
Metrics/ParameterLists:
  Exclude:
    - "lib/auther/settings.rb"
