Metrics/AbcSize:
  Exclude:
    - "app/controllers/auther/base_controller.rb"
    - "lib/auther/gatekeeper.rb"
Metrics/LineLength:
  Exclude:
    - "spec/lib/auther/settings_spec.rb"
    - "spec/models/account_spec.rb"
    - "spec/lib/auther/gatekeeper_spec.rb"
    - "spec/lib/auther/cipher_spec.rb"
    - "spec/lib/auther/authenticator_spec.rb"
    - "spec/dummy/config/initializers/auther.rb"
