Style/AndOr:
  EnforcedStyle: conditionals
Style/CaseIndentation:
  IndentOneStep: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/VariableNumber:
  EnforcedStyle: snake_case
Metrics/AbcSize:
  Exclude:
    - "app/controllers/auther/base_controller.rb"
    - "lib/auther/gatekeeper.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*"
Metrics/LineLength:
  Max: 100
  Exclude:
    - "spec/support/dummy/config/initializers/auther.rb"
    - "spec/support/dummy/config/secrets.yml"
Metrics/MethodLength:
  Exclude:
    - "lib/auther/settings.rb"
Metrics/ParameterLists:
  Max: 3
  Exclude:
    - "lib/auther/settings.rb"
