language: ruby
env:
  global:
    - secure: NK8KZ1CHJkTwfXKvLJUSGeVSiQsFkHKyj39ow5m2cPNUCxndjR3eX02ZkKKCj9/5j6VA2Qz8RFyqPQohSkvwfbLdWDR/V9B9Fa2I+rNV5/RespxyT1EOMGSygUEjMsYfuDsXTYUSdz8RR0dyc+Wm5RkPAxyLTK+omHrQ6AJjj/4=
    - JRUBY_OPTS=--2.0
rvm:
- 2.1.0
- 2.2.0
- jruby-1.7.17
gemfile:
- gemfiles/rails-4.1.x.gemfile
- gemfiles/rails-4.2.x.gemfile
before_install:
- gem install minitest -v "~> 4.7"
- rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  slack:
    secure: gAFabzaZsZvP9dl8NOlAaaEQJNRbYlLJAYxkFov3fcgPnApTKJjl4zpe86fh77+346P+kxQhptyYwuE6bxPkHCp/aGruxBiBXJiXvHfg+eUmr4SMCqEUsTZQpVdYPEaBL8cuByF/eqrfiEMa0aRILB1TO5kpeuEXvxdZAZ/s4vI=
