language: ruby
rvm:
- 2.0.0
- 2.1.0
- jruby
- rbx-2
gemfile:
- gemfiles/rails-4.0.x.gemfile
before_install:
  - gem install minitest -v "~> 4.7"
  - rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  webhooks:
    secure: "Qieky8TZgXKip5qh3tYtsL7yOKJsvDj2xC2n11kWrMuJJQSNTGjltSoAmYenHAF06EctsfyiGXzC/aebBM+he/lMrVV5UGlhXfgcdP65L+OO5edhH8jZxP8zn82CKbcs2MpdbFT7yFWvzx43mvb2hinoNjWmg46SGhAC8AMvG8s="
