language: ruby
env:
  CODECLIMATE_REPO_TOKEN:
    secure: XMEfGdh8DP2XULWJ2kmQXdr3lNgiXqZdVaqiM+U394ZX3bgOy/rE0w+6rGJRT5REfMyWaDsC72aUGbZQUYNtB3jHogQ5RtYO6Tz0KELoHqivuRvCSgUvOT+Rkxy8S7HE/rjZQYbn86C2NIwE7BbDiAuyGHRpvpAEYhY/ALiYK8c=
rvm:
- 2.0.0
- 2.1.0
- jruby
- rbx-2
gemfile:
- gemfiles/rails-4.0.x.gemfile
- gemfiles/rails-4.1.x.gemfile
before_install:
- gem install minitest -v "~> 4.7"
- rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  slack:
    secure: gAFabzaZsZvP9dl8NOlAaaEQJNRbYlLJAYxkFov3fcgPnApTKJjl4zpe86fh77+346P+kxQhptyYwuE6bxPkHCp/aGruxBiBXJiXvHfg+eUmr4SMCqEUsTZQpVdYPEaBL8cuByF/eqrfiEMa0aRILB1TO5kpeuEXvxdZAZ/s4vI=
