require "slim-rails"
require "auther/version"
require "auther/settings"
require "auther/null_logger"
require "auther/cipher"
require "auther/keymaster"
require "auther/gatekeeper"
require "auther/engine"
